export const TAB_TITLES = [
  { title: "Introduction", index: 1 },
  { title: "Generating", index: 2 },
  { title: "Reconstructing", index: 3 },
  { title: "Tips and Best Practices", index: 4 },
  { title: "About", index: 5 },
  { title: "Legal", index: 6 },
]

export const INTRODUCTION = {
  title: "Introduction",
  link: "Shamir's secret sharing",
  toolDescription: `Seedhodler is a tool that uses`,
  masterSeedDescription: `
    to generate, split, and rejoin master seeds for cryptocurrency wallets. A master seed is a
    secret string of words that is used to generate the private keys for your cryptocurrency
    addresses. It is important to keep your master seed safe and secure, as anyone who has access
    to it can potentially access and steal your cryptocurrencies.
  `,
  usageDescription: `
    Using Seedhodler, you can split your master seed into multiple pieces, called "shares," and
    store them in different locations. This way, you can ensure that your master seed is secure
    even if one of the shares is lost or stolen. When you want to access your cryptocurrencies,
    you can use Seedhodler to rejoin the shares and retrieve your master seed.
  `,
}

export const GENERATION = {
  title: "Generation",
  firstPrgrph: `                
  To generate a new master seed, click on the "Generate New Seed" button. The seed will be
  generated from scratch by your computer. If you prefer to manually enter a master seed
  that has been generated before, click on the "Enter Existing Seed" button and enter the
  seed in the designated field.
  `,
  secondPrgrph: `
    If you do not want to rely on your computer to generate random numbers, you can activate
    the advanced toolset to manually enter any entropy that is generated by an external
    device, such as dice or cards.
  `,
  thirdPrgrph: `
    Determine how many seed shares you want to create and how many shares are required to
    reconstruct the seed. For example, if you choose to create 5 shares and require 3 shares
    to reconstruct the seed, you can distribute the 5 shares to different locations and only
    need 3 of them to reconstruct the seed.
  `,
  fourthPrgrph: `
    Click the "Split" button to generate the shares. You will be presented with your first
    share, and you can use the arrow button to slide through all of them.
  `,
  fifthPrgrph: `
    Use the export button to print as many forms for your seed shares as you need on your
    printer to fill out your shares. The shares are not printed in the forms because
    otherwise this info may remain in the memory of your printer which is putting your master
    seed at risk.
  `,
  sixthPrgrph: `
    Follow the process to write down all your seeds and perform a check to ensure that you
    have written down all shares. This will take some time, so do not rush through it.
  `,
}

export const RECONSTRUCTING = {
  title: "Reconstructing",
  firstPrgrph: `                
    To reconstruct your master seed using the shares, click on the "Restore" button. You will
    be prompted to enter any of the shares.
  `,
  secondPrgrph: `
    After you have entered the first share, you will be presented with the information on how
    many shares are missing to restore your master seed.
  `,
  thirdPrgrph: `
    After you have entered enough valid shares, you will see the master seed which you can
    then use to import into your (hardware wallet).
  `,
}

export const TIPS_AND_BEST_PRACTICES = {
  title: "Tips and Best Practices",
  firstPrgrph: `                
    Keep your master seed private and offline to prevent unauthorized access to your
    cryptocurrencies.
  `,
  secondPrgrph: `
    Use an offline computer to generate or split your master seed and ensure that it is not
    connected to the internet during the setup process or afterwards when there is a storage
    medium connected. Consider using an offline version of Seedhodler and run on a live USB
    OS.
  `,
  thirdPrgrph: `
    Consider destroying the original master seed after generating its shares, as this reduces
    the risk of a single point of failure in securing your assets. However, make sure to
    verify that all of your Shamir shares are working and stored in a safe location before
    doing so.
  `,
  fourthPrgrph: `
    Store your seed shares in multiple secure locations, such as a physical safe, secure
    storage device, or safe deposit box. You may also choose to share copies with trusted
    friends or family members, but make sure that these individuals do not know each other in
    a way that would allow them to collaborate and restore the master seed without your
    knowledge.
  `,
}

export const ABOUT = {
  title: "About",
  desc: `
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, ullam nesciunt voluptatum
    repellendus nemo natus earum soluta perspiciatis maiores. Optio incidunt molestias magni
    voluptatibus harum beatae voluptas modi iusto sed? Lorem ipsum dolor sit amet consectetur
    adipisicing elit. Iure, ullam nesciunt voluptatum repellendus nemo natus earum soluta
    perspiciatis maiores. Optio incidunt molestias magni voluptatibus harum beatae voluptas modi
    iusto sed? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, ullam nesciunt
    voluptatum repellendus nemo natus earum soluta perspiciatis maiores. Optio incidunt molestias
    magni voluptatibus harum beatae voluptas modi iusto sed?
  `,
}

export const LEGAL = {
  title: "Legal",
  desc: `
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, ullam nesciunt voluptatum
    repellendus nemo natus earum soluta perspiciatis maiores. Optio incidunt molestias magni
    voluptatibus harum beatae voluptas modi iusto sed? Lorem ipsum dolor sit amet consectetur
    adipisicing elit. Iure, ullam nesciunt voluptatum repellendus nemo natus earum soluta
    perspiciatis maiores. Optio incidunt molestias magni voluptatibus harum beatae voluptas modi
    iusto sed? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, ullam nesciunt
    voluptatum repellendus nemo natus earum soluta perspiciatis maiores. Optio incidunt molestias
    magni voluptatibus harum beatae voluptas modi iusto sed?
  `,
}
