name: "Build seedhodler"
on:
  pull_request:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
    - uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a # v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          max-jobs = 10
    - uses: cachix/cachix-action@6a9a34cdd93d0ae4b4b59fd678660efb08109f2f  # v12
      with:
        name: seedhodler-cache
        authToken: '${{ secrets.CACHIX_KEY }}'

    - run: nix flake check -L
